# Generated by Django 5.0.3 on 2024-04-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='source',
            table='source',
        ),
    ]
