# Generated by Django 5.0.3 on 2024-04-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_usersource_source_usersource_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersource',
            old_name='user_id',
            new_name='user',
        ),
    ]
